---
pigeonholes: 
  homeable: false
  required: false
  tables: 
    pigeonholes: |
      
      content_id I4 NOTNULL PRIMARY,
      structure_id I4 NOTNULL PRIMARY
      CONSTRAINT '
      , CONSTRAINT `pigeonholes_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content`( `content_id` )'
      
    pigeonhole_members: |
      
      parent_id I4 NOTNULL PRIMARY,
      content_id I4 NOTNULL PRIMARY
      CONSTRAINT '
      , CONSTRAINT `pigeonhole_members_parent_ref` FOREIGN KEY (`parent_id`) REFERENCES `liberty_content`( `content_id` )
      , CONSTRAINT `pigeonhole_members_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content`( `content_id` )'
      
  sequences: 
    pigeonholes_id_seq: 
      start: 1
  preferences: 
    pigeonholes_display_members: y
    pigeonholes_limit_member_number: 100
    pigeonholes_list_style: table
    pigeonholes_menu_text: Categories
  permissions: 
    p_pigeonholes_view: 
      description: Can view pigeonholes
      level: basic
    p_pigeonholes_insert_member: 
      description: >
        Can insert content into an existing
        pigeonhole
      level: registered
    p_pigeonholes_update: 
      description: Can update pigeonholes
      level: editors
  requirements: 
    liberty: 
      min: 2.1.5
  version: 0.0.0
  description: >
    A Categorisation system that makes it
    easy to keep an overview of your data.
    Has a simple, yet powerful interface for
    categorising multiple pages at once.
  license: 
    html: '<a href="http://www.gnu.org/licenses/licenses.html#LGPL">LGPL</a>'
